Q1: Questions on Basic NumPy Array

In [1]:
#a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Reversed Array:", reversed_arr)

Reversed Array: [5 4 6 3 2 1]


In [2]:
#b) Flatten the NumPy array using any two in-built methods
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
# Method 1: Using flatten()
flat1 = array1.flatten()
print("Flattened using flatten():", flat1)
# Method 2: Using ravel()
flat2 = array1.ravel()
print("Flattened using ravel():", flat2)

Flattened using flatten(): [1 2 3 2 4 5 1 2 3]
Flattened using ravel(): [1 2 3 2 4 5 1 2 3]


In [3]:
#(c) Compare the following NumPy arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
equal = np.array_equal(arr1, arr2)
print("Are arr1 and arr2 equal?:", equal)

Are arr1 and arr2 equal?: True


In [5]:
#d) Find the most frequent value and their index/indices
#i)
import numpy as np
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
values, counts = np.unique(x, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(x == most_frequent)[0]
print("Most frequent in x:", most_frequent)
print("Indices:", indices)
#ii)
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values, counts = np.unique(y, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(y == most_frequent)[0]
print("Most frequent in y:", most_frequent)
print("Indices:", indices)

Most frequent in x: 1
Indices: [0 5 7 8 9]
Most frequent in y: 1
Indices: [0 1 2]


In [9]:
#e) Operations on Matrix
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
#i. Sum of all elements
total_sum = np.sum(gfg)
print("Total Sum:", total_sum)
#ii. Row-wise sum
row_sum = np.sum(gfg, axis=1)
print("Row-wise Sum:\n", row_sum)
#iii. Column-wise sum
col_sum = np.sum(gfg, axis=0)
print("Column-wise Sum:\n", col_sum)

Total Sum: 45
Row-wise Sum:
 [[14]
 [16]
 [15]]
Column-wise Sum:
 [[20  9 16]]


In [14]:
#f) Operations on Matrix
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])
#i. Sum of diagonal elements
diag_sum = np.trace(n_array)
print("Diagonal Sum:", diag_sum)
#ii. Eigenvalues
eigen_values = np.linalg.eigvals(n_array)
print("Eigenvalues:", eigen_values)
#iii. Eigenvectors
eigen_values, eigen_vectors = np.linalg.eig(n_array)
print("Eigenvectors:\n", eigen_vectors)
#iv. Inverse of matrix
inverse = np.linalg.inv(n_array)
print("Inverse:\n", inverse)
#v. Determinant
det = np.linalg.det(n_array)
print("Determinant:", det)


Diagonal Sum: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001


In [16]:
#g) Matrix Multiplication and Covariance
#i. Multiply and find covariance
import numpy as np
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
product1 = np.dot(p1, q1)
cov1 = np.cov(p1.flatten(), q1.flatten())
print("Product (p1 × q1):\n", product1)
print("Covariance between p1 and q1:\n", cov1)
#ii. Multiply and find covariance
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
product2 = np.dot(p2, q2)
cov2 = np.cov(p2.flatten(), q2.flatten())
print("Product (p2 × q2):\n", product2)
print("Covariance between p2 and q2:\n", cov2)

Product (p1 × q1):
 [[16 19]
 [26 31]]
Covariance between p1 and q1:
 [[0.66666667 1.        ]
 [1.         1.66666667]]
Product (p2 × q2):
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance between p2 and q2:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [20]:
#h) Inner, Outer, and Cartesian Product
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
#i. Inner Product
inner = np.inner(x, y)
print("Inner Product:\n", inner)
#ii. Outer Product
outer = np.outer(x, y)
print("Outer Product shape:", outer.shape)
#iii. Cartesian Product
from itertools import product
cartesian = np.array(list(product(x.flatten(), y.flatten())))
print("Cartesian Product:\n", cartesian)

Inner Product:
 [[17 52]
 [13 62]]
Outer Product shape: (6, 6)
Cartesian Product:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [33]:
#Q2: Based on NumPy Mathematics and Statistics
#a)
import numpy as np
array = np.array([[1, -2, 3], [-4, 5, -6]])

abs_array = np.abs(array)
print("Absolute Values:\n", abs_array)

flattened = array.flatten()
p_flat = np.percentile(flattened, [25, 50, 75])
print("Percentiles (Flattened):", p_flat)

p_col = np.percentile(array, [25, 50, 75], axis=0)
print("Percentiles (Column-wise):\n", p_col)

p_row = np.percentile(array, [25, 50, 75], axis=1)
print("Percentiles (Row-wise):\n", p_row)

print("Mean (flattened):", np.mean(flattened))
print("Median (flattened):", np.median(flattened))
print("Std Dev (flattened):", np.std(flattened))

print("Mean (columns):", np.mean(array, axis=0))
print("Median (columns):", np.median(array, axis=0))
print("Std Dev (columns):", np.std(array, axis=0))

#b)
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("Floor:", np.floor(a))
print("Ceil:", np.ceil(a))
print("Truncated:", np.trunc(a))
print("Rounded:", np.round(a))

Absolute Values:
 [[1 2 3]
 [4 5 6]]
Percentiles (Flattened): [-3.5 -0.5  2.5]
Percentiles (Column-wise):
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles (Row-wise):
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean (flattened): -0.5
Median (flattened): -0.5
Std Dev (flattened): 3.8622100754188224
Mean (columns): [-1.5  1.5 -1.5]
Median (columns): [-1.5  1.5 -1.5]
Std Dev (columns): [2.5 3.5 4.5]
Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceil: [-1. -1. -0.  1.  2.  2.  3.]
Truncated: [-1. -1. -0.  0.  1.  1.  3.]
Rounded: [-2. -2. -0.  0.  2.  2.  3.]


In [39]:
#Q3: Based on Searching and Sorting
#a)
import numpy as np
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array)
print("Sorted Array:", sorted_array)
sorted_indices = np.argsort(array)
print("Indices of Sorted Array:", sorted_indices)
smallest_4 = np.sort(array)[:4]
print("4 Smallest Elements:", smallest_4)
largest_5 = np.sort(array)[-5:]
print("5 Largest Elements:", largest_5)
#b)
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
int_elements = array[array == array.astype(int)]
print("Integer Elements Only:", int_elements)
float_elements = array[array != array.astype(int)]
print("Float Elements Only:", float_elements)


Sorted Array: [ 10  16  16  52  54  62 453]
Indices of Sorted Array: [0 3 4 1 5 2 6]
4 Smallest Elements: [10 16 16 52]
5 Largest Elements: [ 16  52  54  62 453]
Integer Elements Only: [1. 2. 3. 2.]
Float Elements Only: [1.2 2.2]


In [45]:
#Q4
import cv2
import numpy as np
def img_to_array(path, save_path="image_array.txt"):
    img_color = cv2.imread(path, cv2.IMREAD_COLOR)
    img_gray = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    if img_color is None:
        print("Image not found or unsupported format.")
        return
    if img_gray.ndim == 2:
        np.savetxt(save_path, img_gray, fmt='%d')
        print("Grayscale image saved as text at", save_path)
    else:
        img_rgb = cv2.cvtColor(img_color, cv2.COLOR_BGR2RGB)
        np.savetxt(save_path, img_rgb.reshape(-1, 3), fmt='%d')
        print("RGB image saved as flattened text at", save_path)


img_to_array("/content/Screenshot 2025-07-17 101726.png")
gray_image_array = np.loadtxt("image_array.txt", dtype=int)
print("Grayscale Image Array:\n", gray_image_array)

rgb_image_array = np.loadtxt("image_array.txt", dtype=int).reshape(-1, 3)
print("RGB Image Array (flattened):\n", rgb_image_array)


Grayscale image saved as text at image_array.txt
Grayscale Image Array:
 [[ 99  99  99 ...  99  99  99]
 [ 53  53  53 ...  53  53  53]
 [255 255 255 ...  44  44  44]
 ...
 [255 255 255 ...  44  44  44]
 [255 255 255 ...  44  44  44]
 [255 255 255 ...  44  44  44]]
RGB Image Array (flattened):
 [[99 99 99]
 [99 99 99]
 [99 99 99]
 ...
 [44 44 44]
 [44 44 44]
 [44 44 44]]
